server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: MAE2020
    url: jdbc:postgresql://localhost:5432/categoriedb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
