server:
  port: 8087
spring:
  profiles:
    active: prod
  application:
    name: reconcilliation-service
  # Configuration du service mail
  mail:
    host: mailer.gov.bf
    port: 587
    username: etraduction@diplomatie.gov.bf
    password: 'EtraductionBit**2024'
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: ${spring.mail.host}
    test-connection: false

# Configuration personnalisée
app:
  storage:
    path: ./datas
  retention:
    enabled: false
    keep-days: 180
    batch-size: 5000
    cron: "0 30 2 * * *"
    mode: ARCHIVE_AND_PURGE
  security:
    attempts:
      # En nombre de minutes
      timeout: 5
      # Nombre de tentatives autorisées.
      max: 5
